# Generated by Django 5.0 on 2023-12-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Database',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
