# Generated by Django 5.0 on 2023-12-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_employee_database_delete_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Databases',
        ),
    ]
